Serverside hidden activities
Testaustime/testaustime-backend pull request #112
Opened 2024-03-12 21:43 UTC by raikasdev

Very epic Rust code. Probably not very good looking and I will be sticking with TS from now.

Adds support for hiding activities for specific projects. This has been implemented client-side with hashes on the VSCode extension but I'd personally prefer to myself see the projects with names. Currently hidden projects can't be distinguished from each other and they will all have a empty string as the project name along with `"hidden": true`.

2024-03-15 09:44 UTC, lajp requested changes
Hi, thanks for the PR!
This is definitely a functionality we want.
Here are some minor things I'd like you to address before we can merge this.

2024-03-15 09:44 UTC, lajp commented on migrations/2024-03-12-174132_serverside_hidden/down.sql
> +
What are these empty lines?

2024-03-15 09:44 UTC, lajp commented on migrations/2024-03-12-174132_serverside_hidden/up.sql
> +
what are these empty lines

2024-03-15 09:44 UTC, lajp commented on src/database/activity.rs
> +                    // Empty string instead of None() to make sure we don't make everything into "undefined" :D
I'm not sure if we wan't to use an empty String here

2024-03-15 09:44 UTC, lajp commented on src/database/activity.rs
> +        // Change hidden entries project name
This is something that could be done in the query

2024-03-15 09:44 UTC, lajp commented on src/api/friends.rs
> +                    inner_heartbeat.project_name = Some("".to_string());
I'd prefer String::new()

2024-03-15 09:44 UTC, lajp commented on src/api/friends.rs
> +                        inner_heartbeat.project_name = Some("".to_string());
String::new() is better imo

2024-03-15 09:44 UTC, lajp commented on src/api/users.rs
> +                    current_heartbeat.heartbeat.project_name = Some("".to_string());
String::new()

2024-03-15 09:45 UTC, lajp commented
Additionally would it be possible for you or someone else (@Eldemarkki) to implement the funcitonality to the [Frontend side](https://github.com/Testaustime/testaustime-frontend) so that we can enable it immediately after merging?

2024-03-15 09:46 UTC, raikasdev commented on migrations/2024-03-12-174132_serverside_hidden/up.sql
> +
I don't know, I used diesel to autogenerate 🤷

2024-03-15 11:53 UTC, lajp commented on migrations/2024-03-12-174132_serverside_hidden/up.sql
> +
Ok, can you just remove them :point_right: :point_left:

2024-03-15 17:36 UTC, raikasdev commented on src/database/activity.rs
> +        // Change hidden entries project name
It could, but the pro-coder catgirl (Antti) thinks it's not worth trying to get the CASE statement with Diesel.

2024-03-16 12:49 UTC, lajp commented
Should we also automatically hide new heartbeats for projects where there exists a hidden project with the same name and from the same user, regardless of what the client says? Or should we just leave the responsibility to the client?

2024-05-27 07:25 UTC, lajp approved these changes

2024-05-27 07:27 UTC, lajp requested changes
Please fix the tests, otherwise lgtm

2024-05-28 09:26 UTC, DrVilepis approved these changes
kabum

2024-05-28 15:20 UTC, lajp approved these changes
Looks good! Thanks for your contribution and sorry for the slow review.

2024-05-28 15:22 UTC, merged