Update APISPEC.md
Testaustime/testaustime-backend pull request #40
Opened 2022-08-11 20:38 UTC by Merkush1

Instead of updating the documentation, I decided to rewrite it in a little more detail in a standardized format. It turned out a little voluminous, I know, I tried to cram as much as possible under expandable content. Better to check out it in visual format. Happy to have some comments from you, i can update to more shorter format or rechange spec. 

Also i had some problems with few endpoints:

1. POST /activity/delete - tried to test it many times but i can't figure it out. Tested it several times, but I still do not understand what is in the body of the request, looking at the code, so this endpoint is poorly described, as soon as we figure it out, I'll update it before the pr

2. Some strange behavior with several endpoints, I'll leave some comments in controllers

2022-08-11 20:48 UTC, DrVilepis approved these changes
Holy poop this is perfect, we will merge this as soon as possible.

Thank you for this amazing contribution!

2022-08-11 20:53 UTC, DrVilepis commented
/activity/delete is in fact not a POST endpoint, its a DELETE, and it currently just takes a single integer, which is the id of a activity. Its kind of a black sheep of the endpoints as it does not take json as input, even though it should. We will fix this in the next release, as this is not the intended way for it to take input.

2022-08-11 21:03 UTC, DrVilepis requested changes

2022-08-11 21:03 UTC, DrVilepis commented on docs/APISPEC.md
> +>*This request is idempotent, it means that you can demote user that is already regular and have in response 200 OK*
This does not seem like this should be here, should be an easy fix.

2022-08-11 21:05 UTC, DrVilepis commented
Could you also possibly write a quick guide/explanation on what/how to document in CONTRIBUTING.md for easier documentation for us/other new contributors in the future.

2022-08-11 21:30 UTC, Merkush1 commented
>Could you also possibly write a quick guide/explanation on what/how to document in CONTRIBUTING.md for easier documentation for us/other new contributors in the future.

Yeah, sure! I'll check out about POST /activity/delete and other comments tomorrow ;)

2022-08-11 21:31 UTC, DrVilepis commented
Thank you! I will be eagerly waiting.

2022-08-13 10:31 UTC, Merkush1 commented
>/activity/delete is in fact not a POST endpoint, its a DELETE, and it currently just takes a single integer, which is the id of a activity

Still getting the same problem. 

1) First request to get activity_id:

```
curl --location --request GET 'https://testaustime.fi/api/users/@me/activity/data' \
--header 'Authorization: Bearer <token>t' | python3 -m json.tool

[
    {
        "id": 39001,
        "start_time": "2022-08-07T16:06:58.154974",
        "duration": 19,
        "project_name": "string1",
        "language": "key1",
        "editor_name": "string",
        "hostname": "string"
    }
]
```

2) Second request to delete:

```
curl --location --request DELETE 'https://testaustime.fi/api/activity/delete' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: text/plain' \
--data-raw '39001' -i

HTTP/1.1 404 Not Found
Server: nginx/1.14.2
Date: Sat, 13 Aug 2022 10:21:58 GMT
Content-Length: 0
Connection: keep-alive
ratelimit-limit: 8
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
ratelimit-reset: 10
ratelimit-remaining: 4
```

2022-08-20 09:34 UTC, lajp requested changes
This is already looking very nice!
The main problem for me is that the apispec uses the path https://testaustime.fi/api when it should use https://api.testaustime.fi which is the official path.

There was also an issue with one of the sample requests which seemed to be wrong.
Fix these and we'll soon be able to merge this beast.

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +Basic path: `https://testaustime.fi/api`
The path should be https://api.testaustime.fi/ instead.
Same path should be used throughout the documentation.

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST https://testaustime.fi/api/auth/register' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/auth/login' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/auth/changeusername' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/auth/changepassword' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/auth/regenerate' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --location --request GET 'https://testaustime.fi/api/users/@me' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --location --request GET 'https://testaustime.fi/api/users/@me/leaderboards' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --location --request GET 'https://testaustime.fi/api/users/@me/activity/data' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request DELETE 'https://testaustime.fi/api/users/@me/delete' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/activity/update' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/activity/update' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/activity/flush' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request DELETE 'https://testaustime.fi/api/activity/delete' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/friends/add' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request GET 'https://testaustime.fi/api/friends/list' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/friends/regenerate' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +--location --request DELETE 'https://testaustime.fi/api/activity/delete' \
Why does the example not include the `curl` command itself.
The endpoint is also incorrect. Shouldn't it be `/friends/remove`?
Additionally change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/create' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/join' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request GET 'https://testaustime.fi/api/leaderboards/<name>' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request DELETE 'https://testaustime.fi/api/leaderboards/{name}' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/{name}/leave' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/{name}/regenerate' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/{name}/promote' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/{name}/demote' \
change path to https://api.testaustime.fi

2022-08-20 09:34 UTC, lajp commented on docs/APISPEC.md
> +curl --request POST 'https://testaustime.fi/api/leaderboards/{name}/kick' \
change path to https://api.testaustime.fi

2022-08-23 23:02 UTC, Merkush1 commented
Done in new commit! Btw though still getting the same problem with activity/delete using right path `https://api.testaustime.fi` , still getting 404 as it was in https://github.com/Testaustime/testaustime-backend/pull/40#issuecomment-1214134465

2022-08-24 04:02 UTC, DrVilepis commented
Yes. Turns out that was flawed routing from our side, that should be an easyish fix.

2022-09-04 22:48 UTC, Merkush1 commented
Hey @DrVilepis , is there anything else that i can fix in this PR, so you would merge this? ^^

2022-09-04 22:53 UTC, DrVilepis commented
There isn't really anything left, we should be able to merge this the moment @lajp is available.

In fact the moment lajp sees this, he can feel free to merge this pr, this looks all good to me.

2022-09-04 22:54 UTC, DrVilepis approved these changes
Seems all good now

2022-09-05 05:28 UTC, lajp approved these changes
LGTM! Thanks once again for your contribution!

2022-09-05 05:30 UTC, merged

2022-09-05 19:19 UTC, Merkush1 commented
Thank you guys, At some point in time I'll make a swagger as a next step!

2022-09-05 19:25 UTC, bluelhf commented
> Thank you guys, At some point in time I'll make a swagger as a next step!

![A meme showcasing a photo of Ernest Khalimov, also known as GigaChad, with the caption "POV: You're Merkush1".](https://user-images.githubusercontent.com/52505120/188504983-6e869d05-a08e-4984-91b7-b849359bc37f.png)

2022-09-05 19:56 UTC, DrVilepis commented
I second this image