feat: show current heartbeat in friend list and when adding a friend
Testaustime/testaustime-backend pull request #67
Opened 2023-02-20 23:04 UTC by Eldemarkki

This PR adds a `status` field to the response of `GET /friends/list` and `POST /friends/add` showing the current heartbeat status of that friend. 

Getting the current heartbeat could be refactored into its own function, but I wasn't sure where to place that so I just copy-pasted it.

Example responses:
`POST /friends/add`:
```json
{
  "username": "testuser2",
  "coding_time": {
    "all_time": 0,
    "past_month": 0,
    "past_week": 0
  },
  "status": {
    "started": "2023-02-21T00:52:56.083467079",
    "duration": 5,
    "heartbeat": {
      "project_name": null,
      "language": null,
      "editor_name": null,
      "hostname": null
    }
  }
}
```

`GET /friends/list`:
```json
[
  {
    "username": "testuser2",
    "coding_time": {
      "all_time": 0,
      "past_month": 0,
      "past_week": 0
    },
    "status": {
      "started": "2023-02-21T01:03:04.610385534",
      "duration": 3,
      "heartbeat": {
        "project_name": null,
        "language": null,
        "editor_name": null,
        "hostname": null
      }
    }
  }
]
```

2023-02-21 14:33 UTC, DrVilepis requested changes

2023-02-21 14:33 UTC, DrVilepis commented on src/api/friends.rs
> +                },
You should probably replace this with .map

2023-02-21 14:33 UTC, DrVilepis commented on src/models.rs
> +
This is a bit unclear, maybe rename this to something like CurrentActivity?

2023-02-21 14:34 UTC, DrVilepis commented
Also please update the documentation.

2023-03-02 17:45 UTC, lajp approved these changes
lgtm

2023-03-06 08:11 UTC, merged